---

- name: install required softwares
  hosts: all
  become: true
  vars:
    pkgs: [docker,nginx]

  tasks:

    - name: install pkgs
      yum:
        name: "{{item}}"
        state: present
      loop: "{{pkgs}}"


    - name: start docker
      systemd_service:
        name: docker
        state: started

    - name: set current publicip
      shell: |
        current_ip=$(curl -s ifconfig.me)
        set_ip=$(sudo grep "server_name" app.conf | cut -d' ' -f6 | tr -d "; \n")
    
        echo "Current IP: '$current_ip'"
        echo "Set IP: '$set_ip'"

        if [[ "$current_ip" = "$set_ip" ]]; then
          echo "Set IP is correct; serving on $current_ip"
        else 
          sudo sed -i "s/$set_ip/$current_ip/g" app.conf
          echo "Set IP updated; now serving on $current_ip"
        fi
      args:
        chdir: /etc/nginx/conf.d
        executable: /bin/bash


      
    - name: start nginx
      service:
        name: nginx
        state: restarted

      
