name: deploy bluegreen
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ansible_setup:
    runs-on: self-hosted
    steps:

      - name: download ansible
        run: sudo yum install ansible -y

      - name: setup localhost in ansible
        run: |
          echo "$(hostname -i) ansible_connection=local" | sudo tee /etc/ansible/hosts

      
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run play
        run: |
          cd /home/ec2-user/actions-runner/_work/todoApp_backend/todoApp_backend
          docker version
          which docker
          docker compose version
          echo $PATH
          sudo ansible-playbook bluegreen_play.yml
          # sleep 10
          # sudo docker compose up -d
          # sudo touch /etc/nginx/conf.d/app.conf
          # sudo cp ./nginxapp.conf /etc/nginx/conf.d/app.conf
          # sudo nginx -s reload


