name: to deploy app backend
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
  DOCKERHUB_TAG: ${{ secrets.DOCKERHUB_TAG }}

jobs:
  
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin' 
          java-version: '17'

      # - name: cache dep
      #   uses: actions/cache@v4.2.3
      #   with:
      #     path: |
      #       ${{ inputs.cache-path }}
      #       ${{ inputs.cache-path-add }}
      #     key: ${{ inputs.cache-prefix }}${{ runner.os }}-jdk${{ inputs.java-version }}-${{ inputs.java-distribution }}-maven${{ inputs.maven-version }}-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ inputs.cache-prefix }}${{ runner.os }}-jdk${{ inputs.java-version }}-${{ inputs.java-distribution }}-maven${{ inputs.maven-version }}-
      # # - name: Setup Maven Action
      # #   uses: s4u/setup-maven-action@v1.18.0

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9


      - name: build_jar
        run: |
          pwd
          cd /home/runner/work/todoApp/todoApp
          mvnw clean package -DskipTests
          cd ./target
          ll


    