name: keep render alive
on:
  workflow_dispatch:
  schedule: 
        - cron: '*/5 * * * *'

jobs:
  pingurl:
    runs-on: ubuntu-latest
    steps:

      - name: pingurl
        run: |
          curl -o /dev/null -s -w "%{http_code}\n" https://todoapp-backend-r7d0.onrender.com/login
          
    
